services:
  mysql:
    image: 'mysql:8.0'
    container_name: adopciones-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-adopciones_db}
      MYSQL_USER: ${MYSQL_USER:-myuser}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-1234}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adopciones-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WAR_FILE: ${WAR_FILE:-target/GR01_1BT3_622_26A-0.0.1-SNAPSHOT.war}
    image: adopciones-sistema:latest
    container_name: adopciones-app
    ports:
      - '8090:8090'
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://adopciones-mysql:3306/${MYSQL_DATABASE:-adopciones_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER:-myuser}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD:-secret}
      SERVER_PORT: 8090
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure


volumes:
  mysql_data:
