services:
  mysql:
    image: 'mysql:8.0'
    container_name: adopciones-mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adopciones-app:
    image: adopciones-sistema:latest
    container_name: adopciones-app
    ports:
      - '8090:8090'
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://adopciones-mysql:3306/adopciones_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true"
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SERVER_PORT: 8090
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
  jenkins_home:
